### ISSUE TITLE
What is the best way to handle errors?

### ISSUE THREAD

**Issue by alexandresgf** [Fischerfredl/flask-expects-json#11]
Hi!

I tried to handle errors using the method `register_error_handler` with the `ValidationError` exception, but it didn't work. So, I would like to know, what is the best way to catch those errors and customize them?

**Comment by Fischerfredl** [comment]
Hi there,

does #4 solve your Problem?

Snippet:

```python
@app.errorhandler(400)
def handle_bad_request(error):
    return make_response(jsonify({'error': error.description}), 400)

# or, without the decorator
app.register_error_handler(400, handle_bad_request)
```

Like in: https://flask.palletsprojects.com/en/1.1.x/errorhandling/#registering

**Comment by Fischerfredl** [comment]
Error handling is now documented in README.md

**Comment by Fischerfredl** [comment]
Error handling is now documented in README.md
