### ISSUE TITLE
How to apply validation for nested object

### ISSUE THREAD

**Issue by vanarajcs** [Fischerfredl/flask-expects-json#12]
schema = {
    'type': 'object',
    'properties': {
        'name': {'type': 'string'},
        'email': {'type': 'string'},
        'user': {
            'type': 'object',
            "properties": {
              "name": {"type": "string"},
            },
        },
    },
    'required': ['name', 'email', 'user.name']
}

I am trying to validate the inside user object properties. But validation is not working as expected

Does it support for nested object validation?

**Comment by Fischerfredl** [comment]
Hi vanarajcs,

I don't know if you have found the answer, but for anyone looking up the issue:

This is the correct way to specify the property user.name as required:

```python
schema = {
    'type': 'object',
    'properties': {
        'name': {'type': 'string'},
        'email': {'type': 'string'},
        'user': {
            'type': 'object',
            'properties': {
                'name': {'type': 'string'},
            },
            'required': ['name']
        },
    },
    'required': ['name', 'email', 'user']
}
```
Notice, that I also set the property `'user'` on the top-level object as required. Depending on your Use-Case you could also leave the property `'user'` as optional. In this case `'user'` is optional, but when a user is given it has to have a property `'name'`.
