### ISSUE TITLE
Expose the ValidationError

### ISSUE THREAD

**Issue by JJK96** [Fischerfredl/flask-expects-json#13]
Currently we can only handle the error that is thrown using `flask.abort` however, it would be useful to be able to access the original error as well since it contains more information about the error.

This extra information could be exposed to the users of an API for example.

**Comment by Fischerfredl** [comment]
Hi JJK96,
the original error is passed to `flask.abort`, which itself passes arguments to `werkzeug.exceptions.HTTPException`. So the original error can be retrieved on `error.description` like this;

```python
from flask import make_response, jsonify
from jsonschema import ValidationError

@ app.errorhandler(400)
def bad_request(error):
    original_error = error.description
    if isinstance(original_error, ValidationError):
        # custom handling
        return make_response(jsonify({'error': original_error.message}), 400)
    return error
```

References:
[Flask - abort](https://flask.palletsprojects.com/en/1.1.x/api/#flask.abort)
[werkzeug - HTTPException](https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/#werkzeug.exceptions.BadRequest)

**Comment by JJK96** [comment]
You're right indeed, this works.

However, I have no idea how this works.
I looked into the source code of `werkzeug.exceptions.abort` and it doesn't look like the second argument is arriving in the right location. 
But anyway, it works, so that's okay.
