### ISSUE TITLE
Add support for 'minimum' and 'maximum'

### ISSUE THREAD

**Issue by musa11971** [Fischerfredl/flask-expects-json#21]
Feature request: It would be nice if you could validate using a minimum and maximum modifier.  

In the example below, the string length of name should be a minimum of 3 and maximum of 255 characters. In the case of a number: the age should be a minimum of 18 and maximum of 100.

```python
schema = {
    'type': 'object',
    'properties': {
        'name': {'type': 'string', 'minimum': 3, 'maximum': 255},
        'email': {'type': 'string', 'minimum': 1, 'maximum': 255},
        'age': {'type': 'number', 'minimum': 18, 'maximum': 100}
    },
    'required': ['email', 'password']
}


@app.route('/register', methods=['POST'])
@expects_json(schema)
def register():
    # ...
```

What are your thoughts? Is this planned, or maybe not implemented for a reason? May PR this if there is a positive response and I have the time to add it.

**Comment by Fischerfredl** [comment]
Hi musa11971,

this library is a wrapper for [JSON schema](https://json-schema.org/), specifically the [jsonschema](https://python-jsonschema.readthedocs.io/en/stable/) python implementation. String length is covered by the specification through the keys `minLength` and `maxLength` ([spec](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.3)).
