### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by skapin** [Fischerfredl/flask-expects-json#4]
For some security reason, can we pass a parameter to decorator to avoid getting missing parameter on error code (on required field) ? : 
for : 
`{
	"hjkl":42
}`

i get : 

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>'username' is a required property</p>`

i would like something WITHOUT the line `<p>'username' is a required property</p>`

**Comment by Fischerfredl** [comment]
Hi skapin, thank you for your question.

This package uses `flask.abort(400, e.message)` to let flask handle the response. You could register a custom errorhandler to intercept the errormessage.

I usually register an errorhandler to generate JSON responses:
```
from flask import make_response, jsonify

@app.errorhandler(400)
    def bad_request(error):
        return make_response(jsonify({'error': error.description}), 400)
```

You can also return an html template here and rewrite the error messages.

You could also return different messages for debug mode vs. production by checking `flask.current_app.config['DEBUG']` but personally i don't like such different behaviours for debug mode.
