### ISSUE TITLE
Add path to Flask response?

### ISSUE THREAD

**Issue by daynebatten** [Fischerfredl/flask-expects-json#5]
Would you be open to adding the path (I believe what I'm thinking of is absolute_schema_path from jsonschema, but I'd have to check) for the offending item to the Flask response? Would really help with debugging to know which element was problematic, in addition to why it was problematic.

I can open a PR if you'd like.

**Comment by Fischerfredl** [comment]
Hi daynebatten,
thanks for your feedback. I am always open to improve this package. A PR would be very welcomed :wink:

**Comment by daynebatten** [comment]
Thanks! See my PR.

https://github.com/Fischerfredl/flask-expects-json/pull/6

**Comment by Fischerfredl** [comment]
Added in 1.4.0
