### ISSUE TITLE
Reply errors in JSON

### ISSUE THREAD

**Issue by vermaat** [Fischerfredl/flask-expects-json#8]
Currently, the decorator returns the error in HTML format. 

Feature request:
Support to return the error in JSON format would be great (for API usage).

Or can somebody suggest me how to manually change HTML to JSON output?

**Comment by vermaat** [comment]
Nevermind, fixed. i didnt check the closed issues.
https://github.com/Fischerfredl/flask-expects-json/issues/4

**Comment by Fischerfredl** [comment]
Hi vermaat, thank you for mentioning. 

I think this is a valid issue as this feature is not an obvious one. It should be documented in the Readme. 

So I will leave this open until I get time to add a description. Of course I am always open to pull requests.
