### ISSUE TITLE
Non-body HTTP requests trigger abort [Bug]

### ISSUE THREAD

**Issue by mtheos** [Fischerfredl/flask-expects-json#9]
HEAD, GET, and DELETE requests don't have bodies, and Flask won't allow you to define separate functions to handle GET/POST requests.

Request:
Whitelist non-body requests and allow them through without validating

**Comment by mtheos** [comment]
I would find it very odd to receive a body with a GET request, and other than circumventing checks or doing "weird stuff" I can' think when it would ever happen.

I was probably using the same function name when I split it up which is why it failed.

Not a bug then, but I still think it's a good feature to have a named parameter.
For backwards compatibility, an ignore list with a default value might be best?

**Comment by Fischerfredl** [comment]
Alright a named parameter is it then. Do you want to alter your pull request or should I implement it?

By default I would like the validation to be run on all requests as that is the current behavior.

**Comment by mtheos** [comment]
I've just updated my pull request, along with unit  tests for the current behaviour.

**Comment by Fischerfredl** [comment]
Very nice work! Thank you a lot. I will bump the version immediately.
